name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    name: ${{ matrix.name }} Python ${{ matrix.python-version }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6] # , 3.7, 3.8]
        config: [Debug, Release]
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
          - os: macOS-latest
            name: MacOS
    if: matrix.name != 'Windows' or matrix.config == 'Debug'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Setup NMake (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Stetup Conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Install Dependencies
        run: |
          conda install numpy libblas libcblas suitesparse plotly -y

      - name: Envs (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "CMAKE_GENERATOR=NMake Makefiles" >> $GITHUB_ENV
          echo "CXX=cl.exe" >> $GITHUB_ENV
          echo "CC=cl.exe" >> $GITHUB_ENV
          conda init powershell

      - name: Build (Debug)
        if: matrix.config == 'Debug'
        run: |
          python setup.py build --debug install

      - name: Build (Release)
        if: matrix.config == 'Release'
        run: |
          python setup.py build install

      - name: Tests
        if: matrix.name != 'MacOS' # macos segfaults???
        run: |
          python test/test_bending.py
          python test/test_gravity.py
          python test/test_inflation.py
          python test/test_plane_hole.py
